name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Make sure the code is checked out.

      - name: Set up Python
        uses: actions/setup-python@v4 # Set up Python version.
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies.

      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/download.sh | bash  # Install Railway CLI.

      - name: Log in to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}  # Authenticate with Railway.

      - name: Deploy to Railway
        run: |
          railway up --project ${{ secrets.RAILWAY_PROJECT_ID }}  # Deploy the application.
