name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_DNS}}
          key: ${{secrets.EC2_SSH_KEY}}
          username: ${{secrets.USERNAME}}
          script: |
            echo "Starting deployment..."
            
            # Navigate to project directory
            cd fastapi-book-project
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            
            # Setup virtual environment
            echo "Setting up virtual environment..."
            if [ ! -d "venv" ]; then
                python3 -m venv venv
            fi
            source venv/bin/activate
            
            # Install dependencies
            echo "Installing dependencies..."
            python -m pip install --upgrade pip
            pip install --force-reinstall -r requirements.txt
            
            # Stop existing application (force kill)
            echo "Stopping existing application..."
            pkill -9 -f "uvicorn main:app" || true
            sleep 2  # Allow time for termination
            
            # Ensure port 8000 is free