name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_DNS}}
          key: ${{secrets.EC2_SSH_KEY}}
          username: ${{secrets.USERNAME}}
          script: |
            echo "Starting deployment..."
            
            # Navigate to project directory
            cd fastapi-book-project
            
            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            
            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv || exit 1
            source venv/bin/activate || exit 1
            
            # Upgrade pip and install dependencies
            python -m pip install --upgrade pip || exit 1
            pip install fastapi uvicorn || exit 1
            pip install -r requirements.txt || exit 1
            
            # Stop existing application
            PID_FILE="app.pid"
            if [ -f $PID_FILE ]; then
                kill -9 $(cat $PID_FILE) || true
                rm $PID_FILE
            fi
            
            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 & echo $! > $PID_FILE
            
            # Wait for application to start
            sleep 5
            
            # Verify the application is running
            if ! curl -s http://localhost:8000/health; then
                echo "Application failed to start"
                tail -n 50 app.log
                exit 1
            fi
            
            echo "Deployment completed successfully"