name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST_DNS}}
          key: ${{secrets.EC2_SSH_KEY}}
          username: ${{secrets.USERNAME}}
          script: |
            echo "Starting deployment..."

            # Navigate to project directory
            cd fastapi-book-project

            # Pull latest changes (force update)
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            # Debug: Print latest commit
            echo "Latest commit:"
            git log -1

            # Setup virtual environment
            echo "Setting up virtual environment..."
            if [ ! -d "venv" ]; then
                python3 -m venv venv
            fi
            source venv/bin/activate

            # Install/update dependencies
            echo "Installing dependencies..."
            python -m pip install --upgrade pip
            pip install --force-reinstall -r requirements.txt

            # Stop existing application (reliable kill)
            echo "Stopping existing application..."
            pkill -f "uvicorn main:app" || true

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            # Wait and check health
            timeout=15
            while [ $timeout -gt 0 ]; do
                if curl -s http://localhost:8000/healthcheck; then
                    echo "Application started successfully"
                    exit 0
                fi
                sleep 1
                timeout=$((timeout - 1))
            done

            # If health check fails
            echo "ERROR: Application failed to start"
            tail -n 50 app.log
            exit 1
