name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            echo "Starting deployment..."
            
            cd /home/ubuntu/fastapi-book-project || {
              git clone https://github.com/Anonymous2024-spec/fastapi-book-project.git /home/ubuntu/fastapi-book-project
              cd /home/ubuntu/fastapi-book-project
            }

            # Pull latest changes
            git reset --hard HEAD
            git pull origin main

            # Setup virtual environment
            python3 -m venv venv || true
            source venv/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Gracefully stop existing application
            if pgrep -f "uvicorn main:app" > /dev/null; then
              echo "Stopping existing application..."
              pkill -f "uvicorn main:app"
              sleep 5  # Give it time to shutdown
            else
              echo "No existing application running"
            fi

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &

            # Verify application started
            sleep 5
            if curl -s http://localhost:8000/docs > /dev/null; then
              echo "Application started successfully"
            else
              echo "Application failed to start"
              tail -n 50 app.log
              exit 1
            fi