name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Deploy to server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            echo "Starting deployment..."

            # Navigate to project directory
            if [ ! -d "/home/ubuntu/fastapi-book-project" ]; then
              git clone https://github.com/Anonymous2024-spec/fastapi-book-project.git /home/ubuntu/fastapi-book-project
            fi
            cd /home/ubuntu/fastapi-book-project

            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git pull origin main

            # Setup virtual environment
            echo "Setting up virtual environment..."
            python3 -m venv venv
            source venv/bin/activate

            # Upgrade pip
            python -m pip install --upgrade pip

            # Install dependencies
            echo "Installing dependencies..."
            pip install -r requirements.txt

            # Stop existing application if running
            echo "Stopping existing application..."
            ps aux | grep 'uvicorn main:app' | awk '{print $2}' | xargs kill || echo "No existing process found"

            # Start application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "Application started successfully"
